#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright 2025 Edgecast Cloud LLC.
#

#
# Alpine Linux nocloud image configuration
#

VERSION = 3.23.2
URL = https://dl-cdn.alpinelinux.org/alpine/v3.23/releases/cloud/nocloud_alpine-$(VERSION)-x86_64-uefi-cloudinit-r0.qcow2
CHECKSUM =
