#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright 2025 Edgecast Cloud LLC.
#

#
# FreeBSD nocloud image configuration
#

VERSION = 15.0
URL = https://download.freebsd.org/releases/VM-IMAGES/$(VERSION)-RELEASE/amd64/Latest/FreeBSD-$(VERSION)-RELEASE-amd64-BASIC-CLOUDINIT-zfs.raw.xz
CHECKSUM = 45febaec571bc9f5917ecd7833d8cff3f7cb049c1d13ad99ce3067a6c9a17b25
