#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright 2025 Edgecast Cloud LLC.
#

#
# Talos Linux nocloud image configuration
#
# Note: This schematic includes the ZFS extension for Talos.
#

VERSION = 1.12.2
SCHEMATIC_ID = 376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
URL = https://factory.talos.dev/image/$(SCHEMATIC_ID)/v$(VERSION)/nocloud-amd64.raw.xz
CHECKSUM = dd44b4353fcc87e966d137f18c443f27036978becb59ee7d585307734cdad5f6
