#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright 2025 Edgecast Cloud LLC.
#

#
# Talos Linux nocloud image configuration
#
# Note: This schematic includes the ZFS extension for Talos.
#

VERSION = 1.12.0
SCHEMATIC_ID = ff30a5d42f0924818fd48feac4574eaca76308df73adbfc45308c63e764da283
URL = https://factory.talos.dev/image/$(SCHEMATIC_ID)/v$(VERSION)/nocloud-amd64.raw.xz
CHECKSUM = 690f169ab648407fdc7ecb2c5d635b303feb789242fbb5149263f9fdae0b1ab2
