#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright 2025 Edgecast Cloud LLC.
#

#
# Debian 13 (trixie) nocloud image configuration
#

VERSION = 13
CODENAME = trixie
BUILD = 20260112-2355
URL = https://cloud.debian.org/images/cloud/$(CODENAME)/$(BUILD)/debian-$(VERSION)-genericcloud-amd64-$(BUILD).raw
CHECKSUM =
